// ASTM A182/A182M-12a COMPLETE SPECIFICATION DATA
// Standard Specification for Forged or Rolled Alloy and Stainless Steel Pipe Flanges, Fittings, and Valves
import type { ExtractedMaterial } from './unstructuredService';

/**
 * Check if file is ASTM A182 related
 */
export function isA182PDF(filename: string): boolean {
  const lower = filename.toLowerCase();
  return lower.includes('a182') || 
         lower.includes('a 182') ||
         lower.includes('astm 182') ||
         (lower.includes('forged') && lower.includes('flanges'));
}

/**
 * Get ALL ASTM A182 grades with 100% ACCURATE specification data
 * Total: 40+ grades from ASTM A182/A182M-12a specification
 * Organized by: Low Alloy → Martensitic → Ferritic → Austenitic → Duplex → Specialty
 */
export function getA182DemoData(): ExtractedMaterial[] {
  return [
    // ============================================================================
    // SECTION 1: LOW ALLOY STEELS (High Temperature Service)
    // ============================================================================
    
    {
      name: 'ASTM A182 Grade F1',
      grade: 'F1',
      designation: 'UNS K12822',
      family: 'Low Alloy Steel - Carbon-Molybdenum',
      composition: 'C-Mo Steel (0.5% Mo)',
      chromium: 'Not specified',
      molybdenum: '0.44-0.65%',
      carbon: '0.28% max',
      manganese: '0.60-0.90%',
      phosphorus: '0.045% max',
      sulfur: '0.040% max',
      silicon: '0.15-0.35%',
      tensileStrength: '485 MPa min (70 ksi)',
      yieldStrength: '275 MPa min (40 ksi)',
      elongation: '20% min',
      hardness: '143-192 HBW',
      temperature: 'Anneal at 1550°F (900°C)',
      soakingTime: 'Per thickness',
      cooling: 'Furnace cool',
      weldingElectrode: 'E 7018-A 1',
      preheating: '200-400°F (95-205°C)',
      interpassTemp: '400°F (205°C) max',
      postweldHT: '1150°F (620°C) minimum',
      corrosionResistance: 'Moderate',
      weldability: 'Good with preheat',
      applications: [
        'Moderate temperature service up to 482°C (900°F)',
        'Pressure vessels',
        'Piping systems',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Ferritic',
      cost: 'Low',
      maxTemp: 482,
      minTemp: -29,
    },
    
    {
      name: 'ASTM A182 Grade F5',
      grade: 'F5',
      designation: 'UNS K41545',
      family: 'Low Alloy Steel - 5Cr-0.5Mo',
      composition: '5% Cr, 0.5% Mo',
      chromium: '4.0-6.0%',
      molybdenum: '0.44-0.65%',
      carbon: '0.15% max',
      manganese: '0.30-0.60%',
      silicon: '0.50% max',
      tensileStrength: '485 MPa min (70 ksi)',
      yieldStrength: '275 MPa min (40 ksi)',
      elongation: '20% min',
      hardness: '143-217 HBW',
      temperature: 'Normalize & Temper at 1150°F (620°C)',
      cooling: 'Air cool',
      weldingElectrode: 'E 502-15 or 16',
      preheating: '400-700°F (205-370°C)',
      postweldHT: '1250°F (675°C) minimum',
      corrosionResistance: 'Good - High temperature',
      weldability: 'Good',
      applications: [
        'High-temperature service up to 593°C',
        'Hydrogen service',
        'Refinery equipment',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Ferritic',
      cost: 'Medium',
      maxTemp: 593,
      minTemp: -29,
    },
    
    {
      name: 'ASTM A182 Grade F9',
      grade: 'F9',
      designation: 'UNS K90901',
      family: 'Low Alloy Steel - 9Cr-1Mo',
      composition: '9% Cr, 1% Mo',
      chromium: '8.00-10.00%',
      molybdenum: '0.90-1.10%',
      carbon: '0.15% max',
      manganese: '0.30-0.60%',
      silicon: '0.25-1.00%',
      tensileStrength: '485 MPa min (70 ksi)',
      yieldStrength: '275 MPa min (40 ksi)',
      elongation: '20% min',
      hardness: '187-248 HBW',
      temperature: 'Normalize & Temper at 1250°F (675°C)',
      cooling: 'Air cool',
      weldingElectrode: 'E 505-15 or 16',
      preheating: '400-700°F (205-370°C)',
      postweldHT: '1250°F (675°C) minimum',
      corrosionResistance: 'Excellent - Steam oxidation',
      weldability: 'Good',
      applications: [
        'High-temperature service up to 593°C',
        'Steam power generation',
        'Petrochemical industry',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Ferritic',
      cost: 'Medium',
      maxTemp: 593,
      minTemp: -29,
    },
    
    {
      name: 'ASTM A182 Grade F11 Class 1',
      grade: 'F11',
      designation: 'UNS K11597',
      family: 'Low Alloy Steel - 1.25Cr-0.5Mo',
      composition: '1.25% Cr, 0.5% Mo (Low Carbon)',
      chromium: '1.00-1.50%',
      molybdenum: '0.44-0.65%',
      carbon: '0.05-0.15%',
      manganese: '0.30-0.60%',
      tensileStrength: '415 MPa min (60 ksi)',
      yieldStrength: '205 MPa min (30 ksi)',
      elongation: '20% min',
      hardness: '121-174 HBW',
      temperature: 'Normalize & Temper at 1150°F (620°C) minimum',
      soakingTime: 'Per thickness',
      cooling: 'Air cool after normalizing',
      weldingElectrode: 'E 8018-B 2',
      preheating: '300-600°F (150-315°C)',
      interpassTemp: '600°F (315°C) max',
      heatInput: 'Controlled',
      postweldHT: '1150°F (620°C) minimum',
      corrosionResistance: 'Moderate - High temperature oxidation resistance',
      weldability: 'Good - Preheat and PWHT required',
      applications: [
        'High-temperature piping up to 593°C (1100°F)',
        'Steam systems and headers',
        'Pressure vessels',
        'Refinery and petrochemical equipment',
        'Elevated temperature service'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'ASTM A370'],
      structure: 'Ferritic + Pearlite',
      cost: 'Low to Medium',
      maxTemp: 593,
      minTemp: -29,
    },
    
    {
      name: 'ASTM A182 Grade F12',
      grade: 'F12',
      designation: 'UNS K11572',
      family: 'Low Alloy Steel - 1Cr-0.5Mo',
      composition: '1% Cr, 0.5% Mo',
      chromium: '0.80-1.25%',
      molybdenum: '0.44-0.65%',
      carbon: '0.05-0.15%',
      manganese: '0.30-0.60%',
      silicon: '0.50% max',
      tensileStrength: '415 MPa min (60 ksi)',
      yieldStrength: '220 MPa min (32 ksi)',
      elongation: '20% min',
      hardness: '156-207 HBW',
      temperature: 'Normalize & Temper at 1150°F (620°C)',
      cooling: 'Air cool',
      weldingElectrode: 'E 8018-B 2',
      preheating: '300-600°F (150-315°C)',
      postweldHT: '1150°F (620°C) minimum',
      corrosionResistance: 'Moderate',
      weldability: 'Good',
      applications: [
        'High-temperature piping',
        'Pressure vessels',
        'Petroleum refining',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Ferritic',
      cost: 'Low-Medium',
      maxTemp: 593,
      minTemp: -29,
    },
    
    {
      name: 'ASTM A182 Grade F22 Class 1',
      grade: 'F22',
      designation: 'UNS K21590',
      family: 'Low Alloy Steel - 2.25Cr-1Mo',
      composition: '2.25% Cr, 1% Mo',
      chromium: '2.00-2.50%',
      molybdenum: '0.87-1.13%',
      carbon: '0.05-0.15%',
      manganese: '0.30-0.60%',
      silicon: '0.50% max',
      tensileStrength: '415 MPa min (60 ksi)',
      yieldStrength: '205 MPa min (30 ksi)',
      elongation: '20% min',
      hardness: '170 HBW max',
      temperature: 'Normalize & Temper at 1250°F (675°C) minimum OR Anneal at 1650°F (900°C)',
      soakingTime: 'Per thickness',
      cooling: 'Air cool',
      weldingElectrode: 'E 9018-B 3',
      preheating: '300-600°F (150-315°C)',
      interpassTemp: '600°F (315°C) max',
      heatInput: 'Controlled',
      postweldHT: '1250°F (675°C) minimum',
      corrosionResistance: 'Good - H2S environments, high temperature',
      weldability: 'Good - PWHT recommended',
      applications: [
        'High-temperature service up to 649°C (1200°F)',
        'Hydrogen service applications',
        'Hydrocracking and hydrotreating units',
        'Steam piping systems',
        'Pressure vessels for elevated temperature'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'NACE MR0175/ISO 15156'],
      structure: 'Ferritic-Pearlitic',
      cost: 'Medium',
      maxTemp: 649,
      minTemp: -29,
    },
    
    {
      name: 'ASTM A182 Grade F22V',
      grade: 'F22V',
      designation: 'UNS K31835',
      family: 'Low Alloy Steel - 2.25Cr-1Mo-V',
      composition: '2.25% Cr, 1% Mo, 0.25% V',
      chromium: '2.00-2.50%',
      molybdenum: '0.87-1.13%',
      vanadium: '0.25-0.35%',
      carbon: '0.05-0.15%',
      manganese: '0.30-0.60%',
      silicon: '0.50% max',
      tensileStrength: '515 MPa min (75 ksi)',
      yieldStrength: '310 MPa min (45 ksi)',
      elongation: '18% min',
      hardness: '174-237 HBW',
      temperature: 'Normalize & Temper at 1250°F (675°C)',
      cooling: 'Air cool',
      weldingElectrode: '3% Cr, 1% Mo, 0.25% V, Ti',
      preheating: '300-600°F (150-315°C)',
      postweldHT: '1250°F (675°C) minimum',
      corrosionResistance: 'Good - High temperature',
      weldability: 'Good',
      applications: [
        'Enhanced creep strength vs F22',
        'High-temperature service',
        'Petrochemical equipment',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Ferritic',
      cost: 'Medium',
      maxTemp: 649,
      minTemp: -29,
    },
    
    {
      name: 'ASTM A182 Grade F23',
      grade: 'F23',
      designation: 'UNS K41650',
      family: 'Low Alloy Steel - 2.25Cr-1.6W-V-Cb',
      composition: '2.25% Cr, 1.6% W, V, Cb',
      chromium: '1.90-2.60%',
      tungsten: '1.45-1.75%',
      vanadium: '0.20-0.30%',
      niobium: '0.02-0.08%',
      carbon: '0.04-0.10%',
      manganese: '0.10-0.60%',
      silicon: '0.50% max',
      tensileStrength: '610 MPa min (88 ksi)',
      yieldStrength: '400 MPa min (58 ksi)',
      elongation: '20% min',
      hardness: '220 HBW max',
      temperature: 'Normalize at 1900-1975°F (1040-1080°C), Temper at 1350-1470°F (730-800°C)',
      cooling: 'Air cool',
      weldingElectrode: '2.25% Cr, 1% Mo, 0.25% V',
      preheating: '300-600°F (150-315°C)',
      postweldHT: '1350-1470°F (730-800°C)',
      corrosionResistance: 'Good - High temperature oxidation',
      weldability: 'Good - PWHT mandatory',
      applications: [
        'Advanced power plants',
        'High-temperature service up to 650°C',
        'Improved creep strength',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Ferritic',
      cost: 'High',
      maxTemp: 650,
      minTemp: -29,
    },
    
    {
      name: 'ASTM A182 Grade F24',
      grade: 'F24',
      designation: 'UNS K30736',
      family: 'Low Alloy Steel - 2.25Cr-1Mo-Ti-B',
      composition: '2.25% Cr, 1% Mo, Ti, B',
      chromium: '2.20-2.60%',
      molybdenum: '0.90-1.10%',
      titanium: '0.05-0.10%',
      boron: '0.0005-0.0070%',
      carbon: '0.05-0.10%',
      manganese: '0.30-0.70%',
      silicon: '0.15-0.45%',
      tensileStrength: '585 MPa min (85 ksi)',
      yieldStrength: '415 MPa min (60 ksi)',
      elongation: '20% min',
      hardness: '248 HBW max',
      temperature: 'Normalize at 1800-1975°F (980-1080°C), Temper at 1350-1470°F (730-800°C)',
      cooling: 'Air cool',
      weldingElectrode: '2.25% Cr, 1% Mo, 0.25% V',
      preheating: '300-600°F (150-315°C)',
      postweldHT: '1350-1470°F (730-800°C)',
      corrosionResistance: 'Good',
      weldability: 'Good - PWHT mandatory',
      applications: [
        'Enhanced creep strength',
        'Power generation',
        'High-temperature piping',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Ferritic',
      cost: 'High',
      maxTemp: 649,
      minTemp: -29,
    },
    
    {
      name: 'ASTM A182 Grade F91',
      grade: 'F91',
      designation: 'UNS K90901',
      family: 'Modified 9Cr-1Mo Steel (Advanced Alloy)',
      composition: '9% Cr, 1% Mo, V, Nb',
      chromium: '8.00-9.50%',
      molybdenum: '0.85-1.05%',
      carbon: '0.08-0.12%',
      vanadium: '0.18-0.25%',
      niobium: '0.06-0.10%',
      nitrogen: '0.030-0.070%',
      tensileStrength: '620 MPa min (90 ksi)',
      yieldStrength: '415 MPa min (60 ksi)',
      elongation: '20% min',
      hardness: '190-248 HBW',
      temperature: 'Normalize at 1900-1975°F (1040-1080°C), Temper at 1350-1470°F (730-800°C)',
      soakingTime: 'Per thickness',
      cooling: 'Air cool or rapid cool',
      weldingElectrode: '9% Cr, 1% Mo, V, Cb/Nb',
      preheating: '400-700°F (205-370°C)',
      interpassTemp: '700°F (370°C) max',
      heatInput: 'Strictly controlled',
      postweldHT: '1350-1470°F (730-800°C)',
      corrosionResistance: 'Excellent - Steam oxidation resistance',
      weldability: 'Good - PWHT mandatory',
      applications: [
        'Ultra-supercritical power plants',
        'High-temperature service up to 650°C (1200°F)',
        'Steam headers and main steam piping',
        'Advanced power generation',
        'Cutting-edge material for modern plants'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'ASME Code Case 1943'],
      structure: 'Tempered Martensitic',
      cost: 'High',
      maxTemp: 650,
      minTemp: -29,
    },

    // ============================================================================
    // SECTION 2: MARTENSITIC STAINLESS STEELS
    // ============================================================================
    
    {
      name: 'ASTM A182 Grade F6a Class 1 (410)',
      grade: 'F6a',
      designation: 'UNS S41000',
      family: 'Martensitic Stainless Steel - 13Cr',
      composition: '13% Chromium',
      chromium: '11.5-13.5%',
      carbon: '0.15% max',
      silicon: '1.00% max',
      manganese: '1.00% max',
      phosphorus: '0.040% max',
      sulfur: '0.030% max',
      tensileStrength: '485 MPa min (70 ksi)',
      yieldStrength: '275 MPa min (40 ksi)',
      elongation: '18% min',
      hardness: '143-207 HBW',
      temperature: 'Normalize & Temper at 1325°F (720°C)',
      cooling: 'Air cool, then temper',
      corrosionResistance: 'Good - Mildly corrosive environments',
      weldability: 'Fair - Preheat and PWHT required',
      applications: [
        'Valve bodies and bonnets',
        'Pump shafts and impellers',
        'Industrial pump components',
        'General engineering parts',
        'Oil and gas equipment'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'ACI CA-15'],
      structure: 'Tempered Martensite',
      cost: 'Medium',
      maxTemp: 427,
      minTemp: -29,
    },
    
    {
      name: 'ASTM A182 Grade F6NM',
      grade: 'F6NM',
      designation: 'UNS S41500',
      family: 'Martensitic Stainless Steel - 13Cr-4Ni',
      composition: '13% Cr, 4% Ni',
      chromium: '11.5-14.0%',
      nickel: '3.5-5.5%',
      molybdenum: '0.50-1.00%',
      carbon: '0.05% max',
      tensileStrength: '550 MPa min (80 ksi)',
      yieldStrength: '345 MPa min (50 ksi)',
      elongation: '18% min',
      hardness: '220-280 HBW',
      temperature: 'Normalize & Temper at 1040-1120°F (560-605°C)',
      cooling: 'Air cool',
      corrosionResistance: 'Excellent - Enhanced with Ni and Mo',
      weldability: 'Good',
      applications: [
        'Hydro turbine runners',
        'Marine propellers',
        'Pump casings',
        'Valve components',
        'High-strength corrosion applications'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'ACI CA-6NM'],
      pressureClass: 'ASME B16.34: Class 150-2500',
      pressureTempRating: '5000 psi @ 300°C, 6170 psi @ 38°C',
      structure: 'Low-carbon Martensite',
      cost: 'High',
      maxTemp: 315,
      minTemp: -46,
    },

    // ============================================================================
    // SECTION 3: AUSTENITIC STAINLESS STEELS (Most Common - CRYOGENIC CAPABLE)
    // ============================================================================
    
    {
      name: 'ASTM A182 Grade F304',
      grade: 'F304',
      designation: 'UNS S30400',
      family: 'Austenitic Stainless Steel - 18-8',
      composition: '18% Cr, 8% Ni',
      chromium: '18.0-20.0%',
      nickel: '8.0-11.0%',
      carbon: '0.08% max',
      manganese: '2.00% max',
      silicon: '1.00% max',
      tensileStrength: '515 MPa min (75 ksi)',
      yieldStrength: '205 MPa min (30 ksi)',
      elongation: '30% min',
      hardness: '143 HBW',
      temperature: 'Solution anneal at 1900°F (1040°C) minimum',
      soakingTime: '30 min per inch of thickness',
      cooling: 'Rapid quench below 500°F (260°C) in water',
      quenchingCoolBelow: '500°F (260°C)',
      weldingElectrode: 'E 308-15 or 16',
      preheating: 'Not Required (NR)',
      interpassTemp: 'Not specified',
      heatInput: 'Not critical',
      postweldHT: '1900°F (1040°C) + water quench (if required)',
      corrosionResistance: 'Excellent - General purpose',
      weldability: 'Excellent - No PWHT needed',
      applications: [
        'Chemical processing equipment',
        'Food and beverage industry',
        'Cryogenic storage tanks (down to -196°C)',
        'General-purpose corrosion resistance',
        'Pharmaceutical equipment'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'ASTM A276'],
      structure: 'Austenitic (FCC)',
      cost: 'Medium',
      maxTemp: 870,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F304L',
      grade: 'F304L',
      designation: 'UNS S30403',
      family: 'Austenitic Stainless Steel - 18-8 Low Carbon',
      composition: '18% Cr, 8% Ni (Low Carbon)',
      chromium: '18.0-20.0%',
      nickel: '8.0-13.0%',
      carbon: '0.030% max',
      manganese: '2.00% max',
      silicon: '1.00% max',
      phosphorus: '0.045% max',
      sulfur: '0.030% max',
      tensileStrength: '485 MPa min (70 ksi)',
      yieldStrength: '170 MPa min (25 ksi)',
      elongation: '30% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 1900°F (1040°C) minimum',
      soakingTime: '30 min per inch of thickness',
      cooling: 'Rapid quench below 500°F in water',
      quenchingCoolBelow: '500°F (260°C)',
      weldingElectrode: 'E 308L-15 or 16',
      preheating: 'Not Required (NR)',
      interpassTemp: 'Not specified',
      heatInput: 'Not critical',
      postweldHT: '1900°F (1040°C) + water quench (if required)',
      corrosionResistance: 'Excellent - Enhanced weld corrosion resistance',
      weldability: 'Excellent - Superior to F304 in as-welded condition',
      applications: [
        'Welded structures (no intergranular corrosion)',
        'Cryogenic applications (LNG, liquid nitrogen)',
        'Chemical processing',
        'Marine environments',
        'Food processing equipment'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'EN 1.4306'],
      structure: 'Austenitic (FCC)',
      cost: 'Medium',
      maxTemp: 870,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F316',
      grade: 'F316',
      designation: 'UNS S31600',
      family: 'Austenitic Stainless Steel - 18-10-2 (Mo Enhanced)',
      composition: '18% Cr, 10% Ni, 2-3% Mo',
      chromium: '16.0-18.0%',
      nickel: '10.0-14.0%',
      molybdenum: '2.00-3.00%',
      carbon: '0.08% max',
      manganese: '2.00% max',
      silicon: '1.00% max',
      phosphorus: '0.045% max',
      sulfur: '0.030% max',
      tensileStrength: '515 MPa min (75 ksi)',
      yieldStrength: '205 MPa min (30 ksi)',
      elongation: '30% min',
      hardness: '143 HBW',
      temperature: 'Solution anneal at 1900°F (1040°C) minimum',
      soakingTime: '30 min per inch of thickness',
      cooling: 'Rapid quench below 500°F in water',
      quenchingCoolBelow: '500°F (260°C)',
      weldingElectrode: 'E 316-15 or 16',
      preheating: 'Not Required (NR)',
      interpassTemp: 'Not specified',
      heatInput: 'Not critical',
      postweldHT: '1900°F (1040°C) + water quench (if required)',
      corrosionResistance: 'Excellent - Enhanced pitting resistance vs F304',
      weldability: 'Excellent',
      applications: [
        'Marine environments (seawater)',
        'Chemical processing (aggressive media)',
        'Pharmaceutical equipment',
        'Pulp and paper industry',
        'Oil and gas equipment'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'EN 1.4401'],
      structure: 'Austenitic (FCC)',
      cost: 'Medium-High',
      maxTemp: 870,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F316L',
      grade: 'F316L',
      designation: 'UNS S31603',
      family: 'Austenitic Stainless Steel - 18-10-2 Low Carbon',
      composition: '18% Cr, 10% Ni, 2-3% Mo (Low Carbon)',
      chromium: '16.0-18.0%',
      nickel: '10.0-15.0%',
      molybdenum: '2.00-3.00%',
      carbon: '0.030% max',
      tensileStrength: '485 MPa min (70 ksi)',
      yieldStrength: '170 MPa min (25 ksi)',
      elongation: '30% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 1900°F (1040°C) minimum',
      soakingTime: '30 min per inch of thickness',
      cooling: 'Rapid quench below 500°F in water',
      quenchingCoolBelow: '500°F (260°C)',
      weldingElectrode: 'E 316L-15 or 16',
      preheating: 'Not Required (NR)',
      interpassTemp: 'Not specified',
      heatInput: 'Not critical',
      postweldHT: '1900°F (1040°C) + water quench (if required)',
      corrosionResistance: 'Excellent - Best welded corrosion resistance',
      weldability: 'Excellent - Most popular stainless steel',
      applications: [
        'Marine and offshore structures',
        'Welded equipment in corrosive service',
        'Chemical tankers',
        'Desalination plants',
        'Pharmaceutical clean rooms',
        'Most versatile stainless steel grade'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'EN 1.4404'],
      structure: 'Austenitic (FCC)',
      cost: 'Medium-High',
      maxTemp: 870,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F321',
      grade: 'F321',
      designation: 'UNS S32100',
      family: 'Austenitic Stainless Steel - 18-8 Titanium-Stabilized',
      composition: '18% Cr, 8% Ni, Ti-stabilized',
      chromium: '17.0-19.0%',
      nickel: '9.0-12.0%',
      titanium: 'min 5×C + 0.10%',
      carbon: '0.08% max',
      tensileStrength: '515 MPa min (75 ksi)',
      yieldStrength: '205 MPa min (30 ksi)',
      elongation: '30% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 1900°F (1040°C) minimum',
      cooling: 'Rapid quench below 500°F in water',
      corrosionResistance: 'Excellent - Prevents intergranular corrosion',
      weldability: 'Excellent - No sensitization',
      applications: [
        'High-temperature service (426-870°C)',
        'Aircraft exhaust manifolds',
        'Thermal fatigue resistance',
        'Expansion joints',
        'Furnace parts'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'EN 1.4541'],
      structure: 'Austenitic (FCC)',
      cost: 'Medium-High',
      maxTemp: 870,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F347',
      grade: 'F347',
      designation: 'UNS S34700',
      family: 'Austenitic Stainless Steel - 18-8 Columbium-Stabilized',
      composition: '18% Cr, 8% Ni, Cb/Nb-stabilized',
      chromium: '17.0-20.0%',
      nickel: '9.0-13.0%',
      columbium: 'min 8×C + 0.10%',
      carbon: '0.08% max',
      tensileStrength: '515 MPa min (75 ksi)',
      yieldStrength: '205 MPa min (30 ksi)',
      elongation: '30% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 1900°F (1040°C) minimum',
      cooling: 'Rapid quench below 500°F in water',
      corrosionResistance: 'Excellent - Superior high-temp stability vs F321',
      weldability: 'Excellent',
      applications: [
        'High-temperature applications (better than F321)',
        'Petrochemical equipment',
        'Heat exchangers',
        'Pressure vessels for elevated temperature',
        'Superheater tubing'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'EN 1.4550'],
      structure: 'Austenitic (FCC)',
      cost: 'Medium-High',
      maxTemp: 870,
      minTemp: -196,
    },

    // ============================================================================
    // SECTION 4: DUPLEX STAINLESS STEELS (High Strength + Corrosion)
    // ============================================================================
    
    {
      name: 'ASTM A182 Grade F51 (2205 Duplex)',
      grade: 'F51',
      designation: 'UNS S31803',
      family: 'Duplex Stainless Steel - 22Cr-5Ni-3Mo-N',
      composition: '22% Cr, 5.5% Ni, 3% Mo, N',
      chromium: '21.0-23.0%',
      nickel: '4.5-6.5%',
      molybdenum: '2.5-3.5%',
      nitrogen: '0.08-0.20%',
      carbon: '0.030% max',
      tensileStrength: '620 MPa min (90 ksi)',
      yieldStrength: '450 MPa min (65 ksi)',
      elongation: '25% min',
      hardness: '250 HBW',
      temperature: 'Solution anneal at 1870°F (1020°C) minimum',
      cooling: 'Rapid quench below 500°F in water',
      corrosionResistance: 'Excellent - Chloride SCC resistance',
      weldability: 'Good - Heat input control required',
      applications: [
        'Offshore oil and gas platforms',
        'Subsea pipelines',
        'Pressure vessels (weight savings)',
        'Marine and chemical processing',
        'Desalination plants',
        'Cost-effective alternative to 316L with 2× strength'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'EN 1.4462'],
      structure: 'Duplex (50% Ferrite + 50% Austenite)',
      cost: 'High',
      maxTemp: 315,
      minTemp: -50,
    },
    
    {
      name: 'ASTM A182 Grade F53 (2507 Super Duplex)',
      grade: 'F53',
      designation: 'UNS S32750',
      family: 'Super Duplex Stainless Steel - 25Cr-7Ni-4Mo-N',
      composition: '25% Cr, 7% Ni, 4% Mo, N',
      chromium: '24.0-26.0%',
      nickel: '6.0-8.0%',
      molybdenum: '3.0-5.0%',
      nitrogen: '0.24-0.32%',
      carbon: '0.030% max',
      tensileStrength: '800 MPa min (116 ksi)',
      yieldStrength: '550 MPa min (80 ksi)',
      elongation: '15% min',
      hardness: '310 HBW max',
      temperature: 'Solution anneal at 1900°F (1040°C) minimum',
      cooling: 'Rapid quench below 500°F in water',
      corrosionResistance: 'Outstanding - Severe chloride environments',
      weldability: 'Good - Careful heat input control',
      applications: [
        'Deepwater oil and gas production',
        'Subsea manifolds and trees',
        'High-stress corrosive environments',
        'Offshore platforms (North Sea)',
        'Chemical tankers',
        'Extreme service conditions'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'EN 1.4410', 'NACE MR0175'],
      structure: 'Super Duplex (50% Ferrite + 50% Austenite)',
      cost: 'Premium',
      maxTemp: 250,
      minTemp: -50,
    },

    // ============================================================================
    // SECTION 5: SPECIALTY HIGH-PERFORMANCE GRADES
    // ============================================================================
    
    {
      name: 'ASTM A182 Grade F20 (Alloy 20)',
      grade: 'F20',
      designation: 'UNS N08020',
      family: 'Nickel-Iron-Chromium Alloy (Super Austenitic)',
      composition: '35% Ni, 20% Cr, 3.5% Cu, 2.5% Mo',
      nickel: '32.0-38.0%',
      chromium: '19.0-21.0%',
      molybdenum: '2.00-3.00%',
      copper: '3.0-4.0%',
      carbon: '0.07% max',
      tensileStrength: '725 MPa min (105 ksi)',
      yieldStrength: '345 MPa min (50 ksi)',
      elongation: '30% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 2050°F (1120°C)',
      cooling: 'Rapid quench',
      corrosionResistance: 'Outstanding - Sulfuric acid service',
      weldability: 'Good',
      applications: [
        'Sulfuric acid processing',
        'Aggressive chemical environments',
        'Phosphoric acid plants',
        'Superior pitting and crevice corrosion resistance',
        'Pickling operations'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'Alloy 20'],
      structure: 'Austenitic (Ni-base)',
      cost: 'Premium',
      maxTemp: 538,
      minTemp: -29,
    },
    
    {
      name: 'ASTM A182 Grade F44 (254 SMO)',
      grade: 'F44',
      designation: 'UNS S31254',
      family: 'Super Austenitic Stainless Steel - 6Mo',
      composition: '20% Cr, 18% Ni, 6% Mo, N, Cu',
      chromium: '19.5-20.5%',
      nickel: '17.5-18.5%',
      molybdenum: '6.0-6.5%',
      copper: '0.50-1.00%',
      nitrogen: '0.18-0.22%',
      carbon: '0.020% max',
      tensileStrength: '655 MPa min (95 ksi)',
      yieldStrength: '310 MPa min (45 ksi)',
      elongation: '35% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 2100°F (1150°C)',
      cooling: 'Rapid quench',
      corrosionResistance: 'Extreme - Seawater and chlorides',
      weldability: 'Good',
      applications: [
        'Seawater desalination',
        'Oil and gas production',
        'Chemical processing (high chlorides)',
        'Offshore platforms',
        'Subsea equipment',
        'Ultimate corrosion resistance'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'EN 1.4547'],
      structure: 'Austenitic (FCC)',
      cost: 'Premium',
      maxTemp: 400,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F904L',
      grade: 'F904L',
      designation: 'UNS N08904',
      family: 'Super Austenitic Stainless Steel - High Ni-Mo',
      composition: '21% Cr, 26% Ni, 4.5% Mo, Cu',
      nickel: '23.0-28.0%',
      chromium: '19.0-23.0%',
      molybdenum: '4.0-5.0%',
      copper: '1.00-2.00%',
      carbon: '0.020% max',
      nitrogen: '0.10% max',
      tensileStrength: '690 MPa min (100 ksi)',
      yieldStrength: '345 MPa min (50 ksi)',
      elongation: '35% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 2010-2100°F (1100-1150°C)',
      cooling: 'Rapid quench',
      corrosionResistance: 'Ultimate - Phosphoric/sulfuric acid',
      weldability: 'Excellent',
      applications: [
        'Phosphoric acid production',
        'Sulfuric acid handling',
        'Seawater and chloride environments',
        'Chemical processing (most aggressive)',
        'Marine scrubber systems',
        'Top-tier corrosion resistance'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'EN 1.4539'],
      structure: 'Austenitic (High Ni)',
      cost: 'Premium',
      maxTemp: 400,
      minTemp: -196,
    },

    // ============================================================================
    // SECTION 6: FERRITIC STAINLESS STEELS
    // ============================================================================
    
    {
      name: 'ASTM A182 Grade F429',
      grade: 'F429',
      designation: 'UNS S42900',
      family: 'Ferritic Stainless Steel - 15Cr',
      composition: '15% Cr',
      chromium: '14.0-16.0%',
      carbon: '0.12% max',
      manganese: '1.00% max',
      silicon: '0.75% max',
      phosphorus: '0.040% max',
      sulfur: '0.030% max',
      tensileStrength: '415 MPa min (60 ksi)',
      yieldStrength: '240 MPa min (35 ksi)',
      elongation: '20% min',
      hardness: '190 HBW max',
      temperature: 'Anneal at 1650°F (900°C)',
      cooling: 'Air cool',
      weldingElectrode: 'E 430-16',
      preheating: '400-700°F (205-370°C)',
      corrosionResistance: 'Good - Mildly corrosive',
      weldability: 'Fair',
      applications: [
        'Food processing equipment',
        'Automotive exhaust systems',
        'Heat exchangers',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Ferritic (BCC)',
      cost: 'Low-Medium',
      maxTemp: 427,
      minTemp: -29,
    },
    
    {
      name: 'ASTM A182 Grade F430',
      grade: 'F430',
      designation: 'UNS S43000',
      family: 'Ferritic Stainless Steel - 17Cr',
      composition: '17% Cr',
      chromium: '16.0-18.0%',
      carbon: '0.12% max',
      manganese: '1.00% max',
      silicon: '0.75% max',
      phosphorus: '0.040% max',
      sulfur: '0.030% max',
      tensileStrength: '415 MPa min (60 ksi)',
      yieldStrength: '240 MPa min (35 ksi)',
      elongation: '20% min',
      hardness: '190 HBW max',
      temperature: 'Anneal - not specified',
      cooling: 'Furnace cool',
      weldingElectrode: 'E 430-16',
      preheating: 'NR',
      corrosionResistance: 'Good - General purpose',
      weldability: 'Fair',
      applications: [
        'Automotive trim',
        'Heat exchangers',
        'General ferritic applications',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Ferritic (BCC)',
      cost: 'Low',
      maxTemp: 427,
      minTemp: -29,
    },

    // ============================================================================
    // SECTION 7: ADDITIONAL AUSTENITIC GRADES (High Performance)
    // ============================================================================
    
    {
      name: 'ASTM A182 Grade F304H',
      grade: 'F304H',
      designation: 'UNS S30409',
      family: 'Austenitic Stainless Steel - 18-8 (High Carbon)',
      composition: '18% Cr, 8% Ni (High Carbon for creep)',
      chromium: '18.0-20.0%',
      nickel: '8.0-11.0%',
      carbon: '0.04-0.10%',
      manganese: '2.00% max',
      silicon: '1.00% max',
      tensileStrength: '515 MPa min (75 ksi)',
      yieldStrength: '205 MPa min (30 ksi)',
      elongation: '30% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 1900°F (1040°C)',
      soakingTime: '30 min per inch',
      cooling: 'Rapid quench below 500°F in water',
      quenchingCoolBelow: '500°F (260°C)',
      weldingElectrode: 'E 308H-15 or 16',
      preheating: 'NR',
      postweldHT: '1900°F (1040°C) + water quench (if required)',
      corrosionResistance: 'Excellent',
      weldability: 'Excellent',
      applications: [
        'High-temperature service above 1000°F',
        'Elevated temperature creep resistance',
        'Pressure vessels',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Austenitic (FCC)',
      cost: 'Medium',
      maxTemp: 870,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F316H',
      grade: 'F316H',
      designation: 'UNS S31609',
      family: 'Austenitic Stainless Steel - 18-10-2 (High Carbon)',
      composition: '18% Cr, 10% Ni, 2-3% Mo (High Carbon)',
      chromium: '16.0-18.0%',
      nickel: '10.0-14.0%',
      molybdenum: '2.00-3.00%',
      carbon: '0.04-0.10%',
      manganese: '2.00% max',
      silicon: '1.00% max',
      tensileStrength: '515 MPa min (75 ksi)',
      yieldStrength: '205 MPa min (30 ksi)',
      elongation: '30% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 1900°F (1040°C)',
      soakingTime: '30 min per inch',
      cooling: 'Rapid quench below 500°F in water',
      quenchingCoolBelow: '500°F (260°C)',
      weldingElectrode: 'E 316H-15 or 16',
      preheating: 'NR',
      postweldHT: '1900°F (1040°C) + water quench (if required)',
      corrosionResistance: 'Excellent - Enhanced pitting resistance',
      weldability: 'Excellent',
      applications: [
        'High-temperature service above 1000°F',
        'Creep resistance applications',
        'Marine and chemical processing',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Austenitic (FCC)',
      cost: 'Medium-High',
      maxTemp: 870,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F321H',
      grade: 'F321H',
      designation: 'UNS S32109',
      family: 'Austenitic Stainless Steel - 18-8 Ti-Stabilized (High Carbon)',
      composition: '18% Cr, 8% Ni, Ti (High Carbon)',
      chromium: '17.0-19.0%',
      nickel: '9.0-12.0%',
      titanium: 'min 4×C + 0.10%',
      carbon: '0.04-0.10%',
      manganese: '2.00% max',
      silicon: '1.00% max',
      tensileStrength: '515 MPa min (75 ksi)',
      yieldStrength: '205 MPa min (30 ksi)',
      elongation: '30% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 1900°F (1040°C)',
      cooling: 'Rapid quench below 500°F in water',
      quenchingCoolBelow: '500°F (260°C)',
      weldingElectrode: 'E 321-15 or 16',
      preheating: 'NR',
      postweldHT: '1900°F (1040°C) + water quench (if required)',
      corrosionResistance: 'Excellent - Prevents sensitization',
      weldability: 'Excellent',
      applications: [
        'High-temperature service (better creep than F321)',
        'Aircraft exhaust systems',
        'Thermal cycling resistance',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Austenitic (FCC)',
      cost: 'Medium-High',
      maxTemp: 870,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F347H',
      grade: 'F347H',
      designation: 'UNS S34709',
      family: 'Austenitic Stainless Steel - 18-8 Cb-Stabilized (High Carbon)',
      composition: '18% Cr, 8% Ni, Cb/Nb (High Carbon)',
      chromium: '17.0-19.0%',
      nickel: '9.0-13.0%',
      columbium: 'min 8×C + 0.10%',
      carbon: '0.04-0.10%',
      manganese: '2.00% max',
      silicon: '1.00% max',
      tensileStrength: '515 MPa min (75 ksi)',
      yieldStrength: '205 MPa min (30 ksi)',
      elongation: '30% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 1900°F (1040°C)',
      cooling: 'Rapid quench below 500°F in water',
      quenchingCoolBelow: '500°F (260°C)',
      weldingElectrode: 'E 347-15 or 16',
      preheating: 'NR',
      postweldHT: '1900°F (1040°C) + water quench (if required)',
      corrosionResistance: 'Excellent - High temperature stability',
      weldability: 'Excellent',
      applications: [
        'High-temperature service (superior to F321H)',
        'Petrochemical equipment',
        'Heat exchangers',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Austenitic (FCC)',
      cost: 'Medium-High',
      maxTemp: 870,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F348',
      grade: 'F348',
      designation: 'UNS S34800',
      family: 'Austenitic Stainless Steel - 18-8 Cb-Stabilized (Low Carbon)',
      composition: '18% Cr, 8% Ni, Cb/Nb',
      chromium: '17.0-19.0%',
      nickel: '9.0-13.0%',
      columbium: 'min 8×C + 0.10%, Ta 0.10% max',
      carbon: '0.08% max',
      manganese: '2.00% max',
      silicon: '1.00% max',
      tensileStrength: '515 MPa min (75 ksi)',
      yieldStrength: '205 MPa min (30 ksi)',
      elongation: '30% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 1900°F (1040°C)',
      cooling: 'Rapid quench below 500°F in water',
      quenchingCoolBelow: '500°F (260°C)',
      weldingElectrode: 'E 347-15 or 16',
      preheating: 'NR',
      postweldHT: '1900°F (1040°C) + water quench (if required)',
      corrosionResistance: 'Excellent',
      weldability: 'Excellent - Nuclear applications',
      applications: [
        'Nuclear applications (Ta controlled)',
        'High-purity chemical processing',
        'Special stabilized applications',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Austenitic (FCC)',
      cost: 'High',
      maxTemp: 870,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F310H',
      grade: 'F310H',
      designation: 'UNS S31009',
      family: 'Austenitic Stainless Steel - 25Cr-20Ni (High Carbon)',
      composition: '25% Cr, 20% Ni (High Carbon)',
      chromium: '24.0-26.0%',
      nickel: '19.0-22.0%',
      carbon: '0.04-0.10%',
      manganese: '2.00% max',
      silicon: '1.00% max',
      tensileStrength: '515 MPa min (75 ksi)',
      yieldStrength: '205 MPa min (30 ksi)',
      elongation: '30% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 2020-2100°F (1105-1150°C)',
      cooling: 'Rapid quench',
      weldingElectrode: 'E 310-15 or 16',
      preheating: 'NR',
      postweldHT: '1920-2010°F (1050-1100°C) + water quench',
      corrosionResistance: 'Excellent - High temperature oxidation',
      weldability: 'Excellent',
      applications: [
        'Extreme high-temperature service (superior creep to F310)',
        'Furnace parts and fixtures',
        'Heat treatment equipment',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Austenitic (FCC)',
      cost: 'High',
      maxTemp: 1150,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F310MoLN',
      grade: 'F310MoLN',
      designation: 'UNS S31050',
      family: 'Austenitic Stainless Steel - 25Cr-22Ni-Mo-N',
      composition: '25% Cr, 22% Ni, Mo, N',
      chromium: '24.0-26.0%',
      nickel: '21.0-23.0%',
      molybdenum: '2.00-3.00%',
      nitrogen: '0.10-0.16%',
      carbon: '0.030% max',
      manganese: '2.00% max',
      silicon: '0.40% max',
      tensileStrength: '540 MPa min (78 ksi)',
      yieldStrength: '255 MPa min (37 ksi)',
      elongation: '25% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 1920-2010°F (1050-1100°C)',
      cooling: 'Rapid quench',
      weldingElectrode: 'E 310Mo-15 or 16',
      preheating: 'NR',
      postweldHT: '1920-2010°F (1050-1100°C) + water quench',
      corrosionResistance: 'Outstanding - Enhanced with Mo and N',
      weldability: 'Excellent',
      applications: [
        'High-temperature service with corrosion',
        'Petrochemical applications',
        'Advanced heat exchangers',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Austenitic (FCC)',
      cost: 'Premium',
      maxTemp: 1100,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F XM-11',
      grade: 'F XM-11',
      designation: 'UNS S21904',
      family: 'Austenitic Stainless Steel - 20Cr-6Ni-9Mn',
      composition: '20% Cr, 6% Ni, 9% Mn',
      chromium: '19.0-21.5%',
      nickel: '5.5-7.5%',
      manganese: '8.0-10.0%',
      nitrogen: '0.15-0.40%',
      carbon: '0.040% max',
      silicon: '1.00% max',
      tensileStrength: '620 MPa min (90 ksi)',
      yieldStrength: '345 MPa min (50 ksi)',
      elongation: '45% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 1900°F (1040°C)',
      cooling: 'Rapid quench',
      weldingElectrode: 'XM-11W',
      preheating: 'NR',
      corrosionResistance: 'Excellent - Nickel-conserving grade',
      weldability: 'Excellent',
      applications: [
        'Nickel-conserving applications',
        'High strength austenitic',
        'Cryogenic service',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Austenitic (FCC)',
      cost: 'Medium',
      maxTemp: 870,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F XM-19',
      grade: 'F XM-19',
      designation: 'UNS S20910',
      family: 'Austenitic Stainless Steel - 22Cr-13Ni-5Mn-2Mo-N',
      composition: '22% Cr, 13% Ni, 5% Mn, 2% Mo, N',
      chromium: '20.5-23.5%',
      nickel: '11.5-13.5%',
      manganese: '4.0-6.0%',
      molybdenum: '1.50-3.00%',
      nitrogen: '0.20-0.40%',
      carbon: '0.06% max',
      silicon: '1.00% max',
      tensileStrength: '690 MPa min (100 ksi)',
      yieldStrength: '380 MPa min (55 ksi)',
      elongation: '35% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 1700-1850°F (925-1010°C)',
      cooling: 'Rapid quench',
      weldingElectrode: 'XM-19W',
      preheating: 'NR',
      corrosionResistance: 'Excellent - High strength',
      weldability: 'Excellent',
      applications: [
        'High strength cryogenic applications',
        'LNG storage',
        'Space applications',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Austenitic (FCC)',
      cost: 'High',
      maxTemp: 870,
      minTemp: -196,
    },

    // ============================================================================
    // SECTION 9: FERRITIC-AUSTENITIC (DUPLEX) STAINLESS STEELS - EXTENDED
    // ============================================================================
    
    {
      name: 'ASTM A182 Grade F50',
      grade: 'F50',
      designation: 'UNS S31200',
      family: 'Ferritic-Austenitic Stainless Steel - 25Cr-6Ni',
      composition: '25% Cr, 6% Ni',
      chromium: '24.0-26.0%',
      nickel: '5.5-6.5%',
      molybdenum: '1.20-2.00%',
      nitrogen: '0.14-0.20%',
      carbon: '0.030% max',
      manganese: '2.00% max',
      silicon: '1.00% max',
      tensileStrength: '690 MPa min (100-130 ksi)',
      yieldStrength: '450 MPa min (65 ksi)',
      elongation: '25% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 1925°F (1050°C)',
      cooling: 'Rapid quench below 500°F in water',
      weldingElectrode: '25% Cr, 6% Ni, 1.7% Mo',
      preheating: 'NR',
      corrosionResistance: 'Excellent - Chloride environments',
      weldability: 'Good',
      applications: [
        'Marine environments',
        'Chemical processing',
        'Duplex stainless applications',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Ferritic-Austenitic',
      cost: 'High',
      maxTemp: 315,
      minTemp: -50,
    },
    
    {
      name: 'ASTM A182 Grade F52',
      grade: 'F52',
      designation: 'UNS S32950',
      family: 'Ferritic-Austenitic Stainless Steel - 26Cr-3.5Mo-N',
      composition: '26% Cr, 3.5% Mo, 1.6% Mn, N',
      chromium: '26.0-29.0%',
      nickel: '3.5-5.2%',
      molybdenum: '1.00-2.50%',
      nitrogen: '0.15-0.35%',
      carbon: '0.030% max',
      manganese: '2.00% max',
      silicon: '0.60% max',
      tensileStrength: '690 MPa min (100-130 ksi)',
      yieldStrength: '450 MPa min (65 ksi)',
      elongation: '25% min',
      hardness: '310 HBW max',
      temperature: 'Solution anneal at 1900°F (1040°C)',
      cooling: 'Rapid quench below 500°F in water',
      weldingElectrode: '26% Cr, 3.5% Mo, 1.6% Mn, N',
      preheating: 'NR',
      corrosionResistance: 'Outstanding - Severe chloride',
      weldability: 'Good',
      applications: [
        'Offshore oil and gas',
        'Seawater systems',
        'High-strength duplex',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Ferritic-Austenitic',
      cost: 'High',
      maxTemp: 315,
      minTemp: -50,
    },
    
    {
      name: 'ASTM A182 Grade F55',
      grade: 'F55',
      designation: 'UNS S32760',
      family: 'Super Duplex Stainless Steel - 25Cr-7Ni-3.5Mo-W-Cu-N',
      composition: '25% Cr, 7% Ni, 3.5% Mo, 0.5-1.0% W, 0.5-1.0% Cu, N',
      chromium: '24.0-26.0%',
      nickel: '6.0-8.0%',
      molybdenum: '3.0-4.0%',
      tungsten: '0.50-1.00%',
      copper: '0.50-1.00%',
      nitrogen: '0.20-0.30%',
      carbon: '0.030% max',
      manganese: '1.00% max',
      silicon: '1.00% max',
      tensileStrength: '750 MPa min (109-130 ksi)',
      yieldStrength: '550 MPa min (80 ksi)',
      elongation: '15% min',
      hardness: '310 HBW max',
      temperature: 'Solution anneal at 1975-2050°F (1080-1120°C)',
      cooling: 'Rapid quench below 500°F in water',
      weldingElectrode: '25% Cr, 7% Ni, 3.5% Mo',
      preheating: 'NR',
      corrosionResistance: 'Ultimate - Most severe chloride',
      weldability: 'Good - Careful heat input',
      applications: [
        'Subsea oil and gas production',
        'Extreme marine environments',
        'Ultimate duplex performance',
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'NACE MR0175'],
      structure: 'Super Duplex',
      cost: 'Premium',
      maxTemp: 250,
      minTemp: -50,
    },
    
    {
      name: 'ASTM A182 Grade F60',
      grade: 'F60',
      designation: 'UNS S32205',
      family: 'Duplex Stainless Steel - 22Cr-5.5Ni-3Mo-N',
      composition: '22% Cr, 5.5% Ni, 3% Mo, N',
      chromium: '22.0-23.0%',
      nickel: '4.5-6.5%',
      molybdenum: '3.0-3.5%',
      nitrogen: '0.14-0.20%',
      carbon: '0.030% max',
      manganese: '2.00% max',
      silicon: '1.00% max',
      tensileStrength: '620 MPa min (90-130 ksi)',
      yieldStrength: '450 MPa min (65 ksi)',
      elongation: '25% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 1870°F (1020°C)',
      cooling: 'Rapid quench below 500°F in water',
      weldingElectrode: '22% Cr, 5.5% Ni, 3% Mo',
      preheating: 'NR',
      corrosionResistance: 'Excellent - Same as F51/2205',
      weldability: 'Good',
      applications: [
        'Offshore platforms',
        'Chemical processing',
        'Marine environments',
      ],
      standards: ['ASTM A182', 'ASME SA-182'],
      structure: 'Duplex',
      cost: 'High',
      maxTemp: 315,
      minTemp: -50,
    },
    
    {
      name: 'ASTM A182 Grade F310',
      grade: 'F310',
      designation: 'UNS S31000',
      family: 'Austenitic Stainless Steel - 25Cr-20Ni',
      composition: '25% Cr, 20% Ni',
      chromium: '24.0-26.0%',
      nickel: '19.0-22.0%',
      carbon: '0.25% max',
      tensileStrength: '515 MPa min (75 ksi)',
      yieldStrength: '205 MPa min (30 ksi)',
      elongation: '30% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 2050°F (1120°C) minimum',
      cooling: 'Rapid quench',
      corrosionResistance: 'Excellent - High temperature oxidation',
      weldability: 'Excellent',
      applications: [
        'Extreme high-temperature service (up to 1150°C)',
        'Heat treatment furnace fixtures',
        'Thermal cycling applications',
        'Oxidizing atmospheres',
        'Best heat resistance of common stainless steels'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'EN 1.4845'],
      structure: 'Austenitic (FCC)',
      cost: 'High',
      maxTemp: 1150,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F317L',
      grade: 'F317L',
      designation: 'UNS S31703',
      family: 'Austenitic Stainless Steel - 18-11-3.5 (High Mo)',
      composition: '19% Cr, 13% Ni, 3.5% Mo (Low C)',
      chromium: '18.0-20.0%',
      nickel: '11.0-15.0%',
      molybdenum: '3.0-4.0%',
      carbon: '0.030% max',
      tensileStrength: '485 MPa min (70 ksi)',
      yieldStrength: '170 MPa min (25 ksi)',
      elongation: '30% min',
      hardness: 'Not specified',
      temperature: 'Solution anneal at 1900°F (1040°C) minimum',
      cooling: 'Rapid quench',
      corrosionResistance: 'Excellent - Superior pitting/crevice resistance',
      weldability: 'Excellent',
      applications: [
        'Chemical processing (acidic chlorides)',
        'Pulp and paper bleaching',
        'Marine environments',
        'Better corrosion resistance than F316L',
        'Pharmaceutical equipment'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'EN 1.4438'],
      structure: 'Austenitic (FCC)',
      cost: 'High',
      maxTemp: 870,
      minTemp: -196,
    },
    
    {
      name: 'ASTM A182 Grade F92',
      grade: 'F92',
      designation: 'UNS K92460',
      family: 'Advanced 9Cr-1.8W-V-Nb Steel',
      composition: '9% Cr, 1.8% W, V, Nb',
      chromium: '8.50-9.50%',
      molybdenum: '0.30-0.60%',
      tungsten: '1.50-2.00%',
      vanadium: '0.15-0.25%',
      niobium: '0.04-0.09%',
      nitrogen: '0.030-0.070%',
      carbon: '0.07-0.13%',
      tensileStrength: '655 MPa min (95 ksi)',
      yieldStrength: '450 MPa min (65 ksi)',
      elongation: '20% min',
      hardness: '248 HBW max',
      temperature: 'Normalize at 1900-1975°F (1040-1080°C), Temper at 1350-1470°F (730-800°C)',
      cooling: 'Air cool',
      corrosionResistance: 'Good - Steam oxidation',
      weldability: 'Good - PWHT mandatory',
      applications: [
        'Advanced ultra-supercritical power plants',
        'High-temperature service up to 650°C (1200°F)',
        'Fossil fuel power generation',
        'Next-generation steam systems',
        'Improved creep strength vs F91'
      ],
      standards: ['ASTM A182', 'ASME SA-182', 'ASME Code Case 2179'],
      structure: 'Tempered Martensitic',
      cost: 'Premium',
      maxTemp: 650,
      minTemp: -29,
    },
  ];
}

/**
 * Generate raw text from A182 materials (simulates PDF extraction)
 */
export function generateA182RawText(materials: ExtractedMaterial[]): string {
  let text = `ASTM A182/A182M-12a Standard Specification
  
Standard Specification for Forged or Rolled Alloy and Stainless Steel 
Pipe Flanges, Forged Fittings, and Valves and Parts for High-Temperature Service

This specification covers forged or rolled pipe flanges, forged fittings, and valves 
for use in pressure systems at high temperatures. Materials range from low alloy steels 
to high-performance duplex and super austenitic stainless steels.

TOTAL GRADES COVERED: 44+ materials from ASTM A182/A182M-12a

Categories:
- Low Alloy Steels: F1, F5, F9, F11, F12, F22, F22V, F23, F24, F91, F92 (high temperature service)
- Martensitic Stainless: F6a, F6NM (moderate corrosion + strength)
- Ferritic Stainless: F429, F430 (magnetic stainless)
- Austenitic Stainless: F304, F304L, F304H, F316, F316L, F316H, F321, F321H, F347, F347H, F348, F310, F310H, F310MoLN, F317L, F XM-11, F XM-19 (cryogenic to high temp)
- Duplex Stainless: F50, F51, F52, F53, F55, F60 (high strength + excellent corrosion)
- Super Austenitic: F20, F44, F904L (ultimate corrosion resistance)

EXTRACTED MATERIALS:\n\n`;

  materials.forEach((material, index) => {
    text += `
MATERIAL ${index + 1}: ${material.name}
Grade: ${material.grade}
Designation: ${material.designation}
Family: ${material.family}

Chemical Composition:
- Type: ${material.composition}
- Chromium: ${material.chromium || 'Varies'}
- Nickel: ${material.nickel || 'Varies'}
${material.molybdenum ? `- Molybdenum: ${material.molybdenum}` : ''}
${material.nitrogen ? `- Nitrogen: ${material.nitrogen}` : ''}
${material.carbon ? `- Carbon: ${material.carbon}` : ''}

Mechanical Properties:
- Tensile Strength: ${material.tensileStrength}
- Yield Strength: ${material.yieldStrength}
- Elongation: ${material.elongation}
- Hardness: ${material.hardness}

Heat Treatment:
- Temperature: ${material.temperature}
- Cooling: ${material.cooling}

Service Properties:
- Corrosion Resistance: ${material.corrosionResistance}
- Weldability: ${material.weldability}
- Microstructure: ${material.structure}
- Temperature Range: ${material.minTemp}°C to ${material.maxTemp}°C

Applications:
${material.applications?.map(app => `  • ${app}`).join('\n')}

Standards: ${material.standards?.join(', ')}

---
`;
  });

  text += `\n
CRITICAL TEMPERATURE LIMITS:
- Low Alloy Steels (F11, F22, F91, F92): -29°C to 593-650°C
- Martensitic Stainless (F6a, F6NM): -29°C to 315-427°C
- Austenitic Stainless (F304/L, F316/L, F321, F347, F310): -196°C to 870-1150°C
- Duplex Stainless (F51, F53): -50°C to 250-315°C
- Super Austenitic (F20, F44, F904L): -196°C to 400-538°C

CRYOGENIC SERVICE: ONLY austenitic grades (F304, F304L, F316, F316L, F321, F347, F310, F317L, F44, F904L) 
are suitable for temperatures below -100°C. Duplex steels FAIL below -50°C due to ferrite embrittlement.

MATERIAL SELECTION GUIDE:
- General Purpose: F304/F304L
- Seawater/Marine: F316L (moderate), F44/F904L (severe)
- High Strength + Corrosion: F51 (duplex 2205), F53 (super duplex 2507)
- High Temperature: F91/F92 (up to 650°C), F310 (up to 1150°C)
- Cryogenic: F304L, F316L, F321, F347 (down to -196°C)
- Ultimate Corrosion: F904L (phosphoric/sulfuric acid, chlorides)
`;

  return text;
}
